"""
Django settings for Project1 project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zbe&8=la-cnfw!(!_ei0mrlg_qiwut#3lzyf70)bjzcni1jy80'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App1',
    'allauth',
    'allauth.account',
    'allauth.mfa',
    'django_countries',
    'django_filters',
    'django_unicorn',
    'sudo',
    'webauthn',
    'django.contrib.humanize'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'sudo.middleware.SudoMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS=os.path.join(BASE_DIR/'static'),

STATIC_ROOT=BASE_DIR/'staticfiles'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

LOGIN_REDIRECT_URL='/'
# ALLAUTH
ACCOUNT_SIGNUP_FIELDS=['username*','email*','email2*','password1*','password2*']
ACCOUNT_EMAIL_VERIFICATION='mandatory'
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED=True
ACCOUNT_EMAIL_NOTIFICATIONS=True
ACCOUNT_SIGNUP_HONEYPOT_FIELD='address'
ACCOUNT_LOGIN_BY_CODE_ENABLED=True
ACCOUNT_LOGIN_BY_CODE__TRUST_ENABLED=True
ACCOUNT_LOGIN_BY_CODE_MAX_ATTEMPTS=3
ACCOUNT_LOGIN_BY_CODE_REQUIRED=True
ACCOUNT_LOGIN_BY_CODE_SUPPORT_RESEND=True
ACCOUNT_LOGIN_METHODS={'email' or 'username'}
ACCOUNT_LOGIN_TIMEOUT=300
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE=True
ACCOUNT_PASWORD_RESET_BY_CODE_ENABLED=True
ACCOUNT_PASSWORD_RESET_TIMEOUT=120
ACCOUNT_REAUTHENTICATE_REQUIRED=True

# MFA
MFA_SUPPORTED_TYPES=['webauthn','recovery_codes','totp']
MFA_PASSKEY_LOGIN_ENABLED=True
MFA_PASSKEY_SIGNUP_ENABLED=True
MFA_WEBAUTHN_ALLOW_INSECURE_ORIGIN=True

# SESSIONS
import datetime
SESSION_TIME_OUT=datetime.timedelta(minutes=10)
SESSION_EXPIRE_AT_BROWSER_CLOSE=True


SESSION_COOKIE_SAMESITE='Strict'
CSRF_COOKIE_SAMESITE='Strict'
SESSION_COOKIE_HTTPONLY=True